[package]
name = "hammster2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.12.1"
iced_core = "0.12.3"
halo2_proofs = { version = "0.3.0", features = ["dev-graph"] }
rand_core = "0.6.4"
